export const defaultWeatherData = {
  location: {
    id: 1913296,
    name: "Lahore",
    region: "Punjab",
    country: "Pakistan",
    lat: 31.57,
    lon: 74.29,
    url: "lahore-punjab-pakistan",
    selected: true,
  },
  current: {
    last_updated_epoch: 1716985800,
    last_updated: "2024-05-29 17:30",
    temp_c: 44,
    temp_f: 111.2,
    is_day: 1,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003,
    },
    wind_mph: 10.5,
    wind_kph: 16.9,
    wind_degree: 90,
    wind_dir: "E",
    pressure_mb: 993,
    pressure_in: 29.32,
    precip_mm: 0,
    precip_in: 0,
    humidity: 13,
    cloud: 50,
    feelslike_c: 46.2,
    feelslike_f: 115.2,
    windchill_c: 46.9,
    windchill_f: 116.4,
    heatindex_c: 51.3,
    heatindex_f: 124.4,
    dewpoint_c: -8.4,
    dewpoint_f: 16.9,
    vis_km: 6,
    vis_miles: 3,
    uv: 11,
    gust_mph: 10.8,
    gust_kph: 17.4,
  },
  forecast: {
    forecastday: [
      {
        date: "2024-05-29",
        date_epoch: 1716940800,
        day: {
          maxtemp_c: 47.7,
          maxtemp_f: 117.8,
          mintemp_c: 31.5,
          mintemp_f: 88.8,
          avgtemp_c: 40,
          avgtemp_f: 104,
          maxwind_mph: 9.4,
          maxwind_kph: 15.1,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 6,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 11,
        },
        astro: {
          sunrise: "04:59 AM",
          sunset: "07:01 PM",
          moonrise: "No moonrise",
          moonset: "10:13 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: 69,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1716922800,
            time: "2024-05-29 00:00",
            temp_c: 35.8,
            temp_f: 96.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 48,
            wind_dir: "NE",
            pressure_mb: 991,
            pressure_in: 29.27,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 8,
            cloud: 0,
            feelslike_c: 34.2,
            feelslike_f: 93.6,
            windchill_c: 35.8,
            windchill_f: 96.5,
            heatindex_c: 34.2,
            heatindex_f: 93.6,
            dewpoint_c: -3.3,
            dewpoint_f: 26,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.2,
            gust_kph: 19.7,
            uv: 1,
          },
          {
            time_epoch: 1716926400,
            time: "2024-05-29 01:00",
            temp_c: 34.5,
            temp_f: 94,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 40,
            wind_dir: "NE",
            pressure_mb: 991,
            pressure_in: 29.27,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 9,
            cloud: 0,
            feelslike_c: 32.5,
            feelslike_f: 90.6,
            windchill_c: 34.5,
            windchill_f: 94,
            heatindex_c: 32.5,
            heatindex_f: 90.6,
            dewpoint_c: -3.2,
            dewpoint_f: 26.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15,
            gust_kph: 24.2,
            uv: 1,
          },
          {
            time_epoch: 1716930000,
            time: "2024-05-29 02:00",
            temp_c: 33.3,
            temp_f: 92,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 45,
            wind_dir: "NE",
            pressure_mb: 992,
            pressure_in: 29.29,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 10,
            cloud: 0,
            feelslike_c: 31.2,
            feelslike_f: 88.2,
            windchill_c: 33.3,
            windchill_f: 92,
            heatindex_c: 31.2,
            heatindex_f: 88.2,
            dewpoint_c: -3,
            dewpoint_f: 26.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.8,
            gust_kph: 17.4,
            uv: 1,
          },
          {
            time_epoch: 1716933600,
            time: "2024-05-29 03:00",
            temp_c: 32.6,
            temp_f: 90.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 60,
            wind_dir: "ENE",
            pressure_mb: 992,
            pressure_in: 29.29,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 10,
            cloud: 0,
            feelslike_c: 30.4,
            feelslike_f: 86.8,
            windchill_c: 32.6,
            windchill_f: 90.7,
            heatindex_c: 30.4,
            heatindex_f: 86.8,
            dewpoint_c: -3.2,
            dewpoint_f: 26.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1,
          },
          {
            time_epoch: 1716937200,
            time: "2024-05-29 04:00",
            temp_c: 32.1,
            temp_f: 89.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 72,
            wind_dir: "ENE",
            pressure_mb: 992,
            pressure_in: 29.3,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 10,
            cloud: 0,
            feelslike_c: 29.8,
            feelslike_f: 85.7,
            windchill_c: 32.1,
            windchill_f: 89.7,
            heatindex_c: 29.8,
            heatindex_f: 85.7,
            dewpoint_c: -3.6,
            dewpoint_f: 25.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1,
          },
          {
            time_epoch: 1716940800,
            time: "2024-05-29 05:00",
            temp_c: 31.5,
            temp_f: 88.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 78,
            wind_dir: "ENE",
            pressure_mb: 992,
            pressure_in: 29.31,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 10,
            cloud: 0,
            feelslike_c: 29.3,
            feelslike_f: 84.7,
            windchill_c: 31.5,
            windchill_f: 88.8,
            heatindex_c: 29.3,
            heatindex_f: 84.7,
            dewpoint_c: -3.8,
            dewpoint_f: 25.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.8,
            gust_kph: 17.4,
            uv: 8,
          },
          {
            time_epoch: 1716944400,
            time: "2024-05-29 06:00",
            temp_c: 32.5,
            temp_f: 90.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 128,
            wind_dir: "SE",
            pressure_mb: 993,
            pressure_in: 29.34,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 10,
            cloud: 4,
            feelslike_c: 30.3,
            feelslike_f: 86.6,
            windchill_c: 32.5,
            windchill_f: 90.5,
            heatindex_c: 30.3,
            heatindex_f: 86.6,
            dewpoint_c: -3.6,
            dewpoint_f: 25.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.4,
            uv: 8,
          },
          {
            time_epoch: 1716948000,
            time: "2024-05-29 07:00",
            temp_c: 35.7,
            temp_f: 96.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 112,
            wind_dir: "ESE",
            pressure_mb: 994,
            pressure_in: 29.35,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 8,
            cloud: 4,
            feelslike_c: 34.1,
            feelslike_f: 93.3,
            windchill_c: 35.7,
            windchill_f: 96.3,
            heatindex_c: 34.1,
            heatindex_f: 93.3,
            dewpoint_c: -3.6,
            dewpoint_f: 25.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.5,
            gust_kph: 8.9,
            uv: 9,
          },
          {
            time_epoch: 1716951600,
            time: "2024-05-29 08:00",
            temp_c: 38.1,
            temp_f: 100.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 330,
            wind_dir: "NNW",
            pressure_mb: 994,
            pressure_in: 29.36,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 7,
            cloud: 8,
            feelslike_c: 37.1,
            feelslike_f: 98.9,
            windchill_c: 38.1,
            windchill_f: 100.5,
            heatindex_c: 37.1,
            heatindex_f: 98.9,
            dewpoint_c: -4.3,
            dewpoint_f: 24.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 9,
          },
          {
            time_epoch: 1716955200,
            time: "2024-05-29 09:00",
            temp_c: 40.8,
            temp_f: 105.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 352,
            wind_dir: "N",
            pressure_mb: 994,
            pressure_in: 29.36,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 6,
            cloud: 8,
            feelslike_c: 41,
            feelslike_f: 105.9,
            windchill_c: 40.8,
            windchill_f: 105.4,
            heatindex_c: 41,
            heatindex_f: 105.9,
            dewpoint_c: -4.4,
            dewpoint_f: 24.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.1,
            gust_kph: 3.3,
            uv: 10,
          },
          {
            time_epoch: 1716958800,
            time: "2024-05-29 10:00",
            temp_c: 43.4,
            temp_f: 110.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 91,
            wind_dir: "E",
            pressure_mb: 994,
            pressure_in: 29.35,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 5,
            feelslike_c: 45.2,
            feelslike_f: 113.3,
            windchill_c: 43.4,
            windchill_f: 110.1,
            heatindex_c: 45.2,
            heatindex_f: 113.3,
            dewpoint_c: -4.4,
            dewpoint_f: 24,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1,
            gust_kph: 1.7,
            uv: 10,
          },
          {
            time_epoch: 1716962400,
            time: "2024-05-29 11:00",
            temp_c: 45.5,
            temp_f: 113.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 160,
            wind_dir: "SSE",
            pressure_mb: 994,
            pressure_in: 29.34,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 2,
            feelslike_c: 48.8,
            feelslike_f: 119.8,
            windchill_c: 45.5,
            windchill_f: 113.9,
            heatindex_c: 48.8,
            heatindex_f: 119.8,
            dewpoint_c: -4.2,
            dewpoint_f: 24.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.1,
            gust_kph: 3.3,
            uv: 11,
          },
          {
            time_epoch: 1716966000,
            time: "2024-05-29 12:00",
            temp_c: 46.5,
            temp_f: 115.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 993,
            pressure_in: 29.32,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 4,
            cloud: 0,
            feelslike_c: 50.5,
            feelslike_f: 123,
            windchill_c: 46.5,
            windchill_f: 115.6,
            heatindex_c: 50.5,
            heatindex_f: 123,
            dewpoint_c: -4.8,
            dewpoint_f: 23.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 11,
          },
          {
            time_epoch: 1716969600,
            time: "2024-05-29 13:00",
            temp_c: 47.1,
            temp_f: 116.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 247,
            wind_dir: "WSW",
            pressure_mb: 992,
            pressure_in: 29.29,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 4,
            cloud: 0,
            feelslike_c: 51.7,
            feelslike_f: 125.1,
            windchill_c: 47.1,
            windchill_f: 116.8,
            heatindex_c: 51.7,
            heatindex_f: 125.1,
            dewpoint_c: -6.2,
            dewpoint_f: 20.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 11,
          },
          {
            time_epoch: 1716973200,
            time: "2024-05-29 14:00",
            temp_c: 47.5,
            temp_f: 117.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 265,
            wind_dir: "W",
            pressure_mb: 991,
            pressure_in: 29.27,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 3,
            cloud: 0,
            feelslike_c: 52.5,
            feelslike_f: 126.4,
            windchill_c: 47.5,
            windchill_f: 117.5,
            heatindex_c: 52.5,
            heatindex_f: 126.4,
            dewpoint_c: -7.9,
            dewpoint_f: 17.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.6,
            gust_kph: 7.5,
            uv: 11,
          },
          {
            time_epoch: 1716976800,
            time: "2024-05-29 15:00",
            temp_c: 47.7,
            temp_f: 117.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 276,
            wind_dir: "W",
            pressure_mb: 990,
            pressure_in: 29.24,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 3,
            cloud: 2,
            feelslike_c: 52.7,
            feelslike_f: 126.9,
            windchill_c: 47.7,
            windchill_f: 117.8,
            heatindex_c: 52.7,
            heatindex_f: 126.9,
            dewpoint_c: -8.5,
            dewpoint_f: 16.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.4,
            gust_kph: 7.1,
            uv: 11,
          },
          {
            time_epoch: 1716980400,
            time: "2024-05-29 16:00",
            temp_c: 47.4,
            temp_f: 117.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 989,
            pressure_in: 29.21,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 3,
            cloud: 2,
            feelslike_c: 52.2,
            feelslike_f: 126,
            windchill_c: 47.4,
            windchill_f: 117.3,
            heatindex_c: 52.2,
            heatindex_f: 126,
            dewpoint_c: -8.4,
            dewpoint_f: 16.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 11,
          },
          {
            time_epoch: 1716984000,
            time: "2024-05-29 17:00",
            temp_c: 44,
            temp_f: 111.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 90,
            wind_dir: "E",
            pressure_mb: 993,
            pressure_in: 29.32,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 13,
            cloud: 50,
            feelslike_c: 51.3,
            feelslike_f: 124.4,
            windchill_c: 46.9,
            windchill_f: 116.4,
            heatindex_c: 51.3,
            heatindex_f: 124.4,
            dewpoint_c: -8.4,
            dewpoint_f: 16.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6,
            vis_miles: 3,
            gust_mph: 10.8,
            gust_kph: 17.4,
            uv: 11,
          },
          {
            time_epoch: 1716987600,
            time: "2024-05-29 18:00",
            temp_c: 45.8,
            temp_f: 114.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 989,
            pressure_in: 29.21,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 3,
            cloud: 0,
            feelslike_c: 49.3,
            feelslike_f: 120.7,
            windchill_c: 45.8,
            windchill_f: 114.4,
            heatindex_c: 49.3,
            heatindex_f: 120.7,
            dewpoint_c: -8.5,
            dewpoint_f: 16.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.8,
            gust_kph: 19,
            uv: 11,
          },
          {
            time_epoch: 1716991200,
            time: "2024-05-29 19:00",
            temp_c: 42.1,
            temp_f: 107.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 321,
            wind_dir: "NW",
            pressure_mb: 990,
            pressure_in: 29.23,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 4,
            cloud: 0,
            feelslike_c: 43.1,
            feelslike_f: 109.6,
            windchill_c: 42.1,
            windchill_f: 107.8,
            heatindex_c: 43.1,
            heatindex_f: 109.6,
            dewpoint_c: -7.8,
            dewpoint_f: 18,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.5,
            gust_kph: 24.9,
            uv: 10,
          },
          {
            time_epoch: 1716994800,
            time: "2024-05-29 20:00",
            temp_c: 40.3,
            temp_f: 104.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 334,
            wind_dir: "NNW",
            pressure_mb: 991,
            pressure_in: 29.25,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 2,
            feelslike_c: 40.3,
            feelslike_f: 104.5,
            windchill_c: 40.3,
            windchill_f: 104.5,
            heatindex_c: 40.3,
            heatindex_f: 104.5,
            dewpoint_c: -7.3,
            dewpoint_f: 18.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15,
            gust_kph: 24.2,
            uv: 1,
          },
          {
            time_epoch: 1716998400,
            time: "2024-05-29 21:00",
            temp_c: 39.1,
            temp_f: 102.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 337,
            wind_dir: "NNW",
            pressure_mb: 991,
            pressure_in: 29.27,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 3,
            feelslike_c: 38.6,
            feelslike_f: 101.4,
            windchill_c: 39.1,
            windchill_f: 102.3,
            heatindex_c: 38.6,
            heatindex_f: 101.4,
            dewpoint_c: -7,
            dewpoint_f: 19.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 1,
          },
          {
            time_epoch: 1717002000,
            time: "2024-05-29 22:00",
            temp_c: 37.8,
            temp_f: 100.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 345,
            wind_dir: "NNW",
            pressure_mb: 992,
            pressure_in: 29.29,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 6,
            cloud: 3,
            feelslike_c: 36.8,
            feelslike_f: 98.3,
            windchill_c: 37.8,
            windchill_f: 100.1,
            heatindex_c: 36.8,
            heatindex_f: 98.3,
            dewpoint_c: -6,
            dewpoint_f: 21.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.5,
            gust_kph: 24.9,
            uv: 1,
          },
          {
            time_epoch: 1717005600,
            time: "2024-05-29 23:00",
            temp_c: 36.7,
            temp_f: 98,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 357,
            wind_dir: "N",
            pressure_mb: 992,
            pressure_in: 29.29,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 7,
            cloud: 4,
            feelslike_c: 35.3,
            feelslike_f: 95.5,
            windchill_c: 36.7,
            windchill_f: 98,
            heatindex_c: 35.3,
            heatindex_f: 95.5,
            dewpoint_c: -4.2,
            dewpoint_f: 24.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.8,
            gust_kph: 30.2,
            uv: 1,
          },
        ],
      },
      {
        date: "2024-05-30",
        date_epoch: 1717027200,
        day: {
          maxtemp_c: 47.3,
          maxtemp_f: 117.1,
          mintemp_c: 31.3,
          mintemp_f: 88.4,
          avgtemp_c: 39.8,
          avgtemp_f: 103.7,
          maxwind_mph: 10.7,
          maxwind_kph: 17.3,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 7,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 11,
        },
        astro: {
          sunrise: "04:59 AM",
          sunset: "07:02 PM",
          moonrise: "12:14 AM",
          moonset: "11:21 AM",
          moon_phase: "Last Quarter",
          moon_illumination: 58,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1717009200,
            time: "2024-05-30 00:00",
            temp_c: 35.7,
            temp_f: 96.2,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 3,
            wind_dir: "N",
            pressure_mb: 992,
            pressure_in: 29.29,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 9,
            cloud: 5,
            feelslike_c: 34,
            feelslike_f: 93.2,
            windchill_c: 35.7,
            windchill_f: 96.2,
            heatindex_c: 34,
            heatindex_f: 93.2,
            dewpoint_c: -2.7,
            dewpoint_f: 27.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.8,
            gust_kph: 30.2,
            uv: 1,
          },
          {
            time_epoch: 1717012800,
            time: "2024-05-30 01:00",
            temp_c: 34.7,
            temp_f: 94.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 346,
            wind_dir: "NNW",
            pressure_mb: 992,
            pressure_in: 29.28,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 10,
            cloud: 4,
            feelslike_c: 32.9,
            feelslike_f: 91.2,
            windchill_c: 34.7,
            windchill_f: 94.5,
            heatindex_c: 32.9,
            heatindex_f: 91.2,
            dewpoint_c: -1.4,
            dewpoint_f: 29.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.4,
            gust_kph: 26.5,
            uv: 1,
          },
          {
            time_epoch: 1717016400,
            time: "2024-05-30 02:00",
            temp_c: 34,
            temp_f: 93.2,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 355,
            wind_dir: "N",
            pressure_mb: 991,
            pressure_in: 29.28,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 11,
            cloud: 3,
            feelslike_c: 32,
            feelslike_f: 89.6,
            windchill_c: 34,
            windchill_f: 93.2,
            heatindex_c: 32,
            heatindex_f: 89.6,
            dewpoint_c: -1,
            dewpoint_f: 30.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16,
            gust_kph: 25.7,
            uv: 1,
          },
          {
            time_epoch: 1717020000,
            time: "2024-05-30 03:00",
            temp_c: 33,
            temp_f: 91.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 357,
            wind_dir: "N",
            pressure_mb: 992,
            pressure_in: 29.28,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 11,
            cloud: 0,
            feelslike_c: 30.8,
            feelslike_f: 87.5,
            windchill_c: 33,
            windchill_f: 91.3,
            heatindex_c: 30.8,
            heatindex_f: 87.5,
            dewpoint_c: -0.8,
            dewpoint_f: 30.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.5,
            gust_kph: 24.9,
            uv: 1,
          },
          {
            time_epoch: 1717023600,
            time: "2024-05-30 04:00",
            temp_c: 32.1,
            temp_f: 89.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 359,
            wind_dir: "N",
            pressure_mb: 992,
            pressure_in: 29.29,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 12,
            cloud: 0,
            feelslike_c: 29.9,
            feelslike_f: 85.9,
            windchill_c: 32.2,
            windchill_f: 89.9,
            heatindex_c: 29.9,
            heatindex_f: 85.9,
            dewpoint_c: -1.1,
            dewpoint_f: 30,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16,
            gust_kph: 25.7,
            uv: 1,
          },
          {
            time_epoch: 1717027200,
            time: "2024-05-30 05:00",
            temp_c: 31.3,
            temp_f: 88.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 2,
            wind_dir: "N",
            pressure_mb: 993,
            pressure_in: 29.32,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 13,
            cloud: 0,
            feelslike_c: 29.1,
            feelslike_f: 84.3,
            windchill_c: 31.3,
            windchill_f: 88.4,
            heatindex_c: 29.1,
            heatindex_f: 84.3,
            dewpoint_c: -0.8,
            dewpoint_f: 30.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 8,
          },
          {
            time_epoch: 1717030800,
            time: "2024-05-30 06:00",
            temp_c: 32.1,
            temp_f: 89.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 14,
            wind_dir: "NNE",
            pressure_mb: 994,
            pressure_in: 29.36,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 12,
            cloud: 0,
            feelslike_c: 29.8,
            feelslike_f: 85.7,
            windchill_c: 32.1,
            windchill_f: 89.7,
            heatindex_c: 29.8,
            heatindex_f: 85.7,
            dewpoint_c: -0.3,
            dewpoint_f: 31.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.2,
            uv: 8,
          },
          {
            time_epoch: 1717034400,
            time: "2024-05-30 07:00",
            temp_c: 34.9,
            temp_f: 94.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 26,
            wind_dir: "NNE",
            pressure_mb: 995,
            pressure_in: 29.38,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 10,
            cloud: 0,
            feelslike_c: 33,
            feelslike_f: 91.5,
            windchill_c: 34.9,
            windchill_f: 94.8,
            heatindex_c: 33,
            heatindex_f: 91.5,
            dewpoint_c: -1,
            dewpoint_f: 30.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.4,
            gust_kph: 7.1,
            uv: 8,
          },
          {
            time_epoch: 1717038000,
            time: "2024-05-30 08:00",
            temp_c: 38,
            temp_f: 100.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 354,
            wind_dir: "N",
            pressure_mb: 995,
            pressure_in: 29.39,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 8,
            cloud: 0,
            feelslike_c: 37,
            feelslike_f: 98.6,
            windchill_c: 38,
            windchill_f: 100.3,
            heatindex_c: 37,
            heatindex_f: 98.6,
            dewpoint_c: -2.3,
            dewpoint_f: 27.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 9,
          },
          {
            time_epoch: 1717041600,
            time: "2024-05-30 09:00",
            temp_c: 40.8,
            temp_f: 105.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 350,
            wind_dir: "N",
            pressure_mb: 995,
            pressure_in: 29.39,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 6,
            cloud: 0,
            feelslike_c: 41.2,
            feelslike_f: 106.1,
            windchill_c: 40.8,
            windchill_f: 105.5,
            heatindex_c: 41.2,
            heatindex_f: 106.1,
            dewpoint_c: -2.8,
            dewpoint_f: 27,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.2,
            gust_kph: 13.2,
            uv: 10,
          },
          {
            time_epoch: 1717045200,
            time: "2024-05-30 10:00",
            temp_c: 43.1,
            temp_f: 109.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 335,
            wind_dir: "NNW",
            pressure_mb: 996,
            pressure_in: 29.4,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 6,
            cloud: 0,
            feelslike_c: 44.8,
            feelslike_f: 112.7,
            windchill_c: 43.1,
            windchill_f: 109.7,
            heatindex_c: 44.8,
            heatindex_f: 112.7,
            dewpoint_c: -2.9,
            dewpoint_f: 26.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.6,
            uv: 10,
          },
          {
            time_epoch: 1717048800,
            time: "2024-05-30 11:00",
            temp_c: 44.9,
            temp_f: 112.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 306,
            wind_dir: "NW",
            pressure_mb: 996,
            pressure_in: 29.4,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 0,
            feelslike_c: 47.8,
            feelslike_f: 118,
            windchill_c: 44.9,
            windchill_f: 112.8,
            heatindex_c: 47.8,
            heatindex_f: 118,
            dewpoint_c: -2.9,
            dewpoint_f: 26.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8,
            gust_kph: 12.9,
            uv: 10,
          },
          {
            time_epoch: 1717052400,
            time: "2024-05-30 12:00",
            temp_c: 46,
            temp_f: 114.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 291,
            wind_dir: "WNW",
            pressure_mb: 995,
            pressure_in: 29.39,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 0,
            feelslike_c: 49.7,
            feelslike_f: 121.4,
            windchill_c: 46,
            windchill_f: 114.8,
            heatindex_c: 49.7,
            heatindex_f: 121.4,
            dewpoint_c: -3.2,
            dewpoint_f: 26.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.7,
            gust_kph: 14.1,
            uv: 11,
          },
          {
            time_epoch: 1717056000,
            time: "2024-05-30 13:00",
            temp_c: 46.8,
            temp_f: 116.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 273,
            wind_dir: "W",
            pressure_mb: 994,
            pressure_in: 29.36,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 4,
            cloud: 0,
            feelslike_c: 51.1,
            feelslike_f: 123.9,
            windchill_c: 46.8,
            windchill_f: 116.2,
            heatindex_c: 51.1,
            heatindex_f: 123.9,
            dewpoint_c: -5.9,
            dewpoint_f: 21.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9,
            gust_kph: 14.5,
            uv: 11,
          },
          {
            time_epoch: 1717059600,
            time: "2024-05-30 14:00",
            temp_c: 47.1,
            temp_f: 116.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 994,
            pressure_in: 29.34,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 4,
            cloud: 0,
            feelslike_c: 51.7,
            feelslike_f: 125,
            windchill_c: 47.1,
            windchill_f: 116.8,
            heatindex_c: 51.7,
            heatindex_f: 125,
            dewpoint_c: -6.5,
            dewpoint_f: 20.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.7,
            gust_kph: 14.1,
            uv: 11,
          },
          {
            time_epoch: 1717063200,
            time: "2024-05-30 15:00",
            temp_c: 47.3,
            temp_f: 117.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 993,
            pressure_in: 29.32,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 3,
            cloud: 0,
            feelslike_c: 52,
            feelslike_f: 125.6,
            windchill_c: 47.3,
            windchill_f: 117.1,
            heatindex_c: 52,
            heatindex_f: 125.6,
            dewpoint_c: -7.4,
            dewpoint_f: 18.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 11,
          },
          {
            time_epoch: 1717066800,
            time: "2024-05-30 16:00",
            temp_c: 47.1,
            temp_f: 116.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 267,
            wind_dir: "W",
            pressure_mb: 992,
            pressure_in: 29.3,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 3,
            cloud: 2,
            feelslike_c: 51.7,
            feelslike_f: 125,
            windchill_c: 47.1,
            windchill_f: 116.8,
            heatindex_c: 51.7,
            heatindex_f: 125,
            dewpoint_c: -8.1,
            dewpoint_f: 17.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.1,
            gust_kph: 17.8,
            uv: 11,
          },
          {
            time_epoch: 1717070400,
            time: "2024-05-30 17:00",
            temp_c: 46.5,
            temp_f: 115.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 261,
            wind_dir: "W",
            pressure_mb: 992,
            pressure_in: 29.3,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 3,
            cloud: 0,
            feelslike_c: 50.6,
            feelslike_f: 123,
            windchill_c: 46.5,
            windchill_f: 115.7,
            heatindex_c: 50.6,
            heatindex_f: 123,
            dewpoint_c: -8.8,
            dewpoint_f: 16.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.3,
            gust_kph: 19.9,
            uv: 11,
          },
          {
            time_epoch: 1717074000,
            time: "2024-05-30 18:00",
            temp_c: 45.4,
            temp_f: 113.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 260,
            wind_dir: "W",
            pressure_mb: 993,
            pressure_in: 29.31,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 3,
            cloud: 0,
            feelslike_c: 48.7,
            feelslike_f: 119.6,
            windchill_c: 45.4,
            windchill_f: 113.7,
            heatindex_c: 48.7,
            heatindex_f: 119.6,
            dewpoint_c: -8.8,
            dewpoint_f: 16.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 11,
          },
          {
            time_epoch: 1717077600,
            time: "2024-05-30 19:00",
            temp_c: 41.5,
            temp_f: 106.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 266,
            wind_dir: "W",
            pressure_mb: 993,
            pressure_in: 29.33,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 4,
            cloud: 0,
            feelslike_c: 42.2,
            feelslike_f: 107.9,
            windchill_c: 41.5,
            windchill_f: 106.7,
            heatindex_c: 42.2,
            heatindex_f: 107.9,
            dewpoint_c: -8.8,
            dewpoint_f: 16.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.5,
            gust_kph: 24.9,
            uv: 10,
          },
          {
            time_epoch: 1717081200,
            time: "2024-05-30 20:00",
            temp_c: 40,
            temp_f: 104,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 994,
            pressure_in: 29.35,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 4,
            cloud: 0,
            feelslike_c: 39.9,
            feelslike_f: 103.8,
            windchill_c: 40,
            windchill_f: 104,
            heatindex_c: 39.9,
            heatindex_f: 103.8,
            dewpoint_c: -8.5,
            dewpoint_f: 16.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.7,
            gust_kph: 20.4,
            uv: 1,
          },
          {
            time_epoch: 1717084800,
            time: "2024-05-30 21:00",
            temp_c: 39.2,
            temp_f: 102.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 306,
            wind_dir: "NW",
            pressure_mb: 994,
            pressure_in: 29.36,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 0,
            feelslike_c: 38.8,
            feelslike_f: 101.9,
            windchill_c: 39.2,
            windchill_f: 102.6,
            heatindex_c: 38.8,
            heatindex_f: 101.9,
            dewpoint_c: -8.2,
            dewpoint_f: 17.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.7,
            gust_kph: 18.9,
            uv: 1,
          },
          {
            time_epoch: 1717088400,
            time: "2024-05-30 22:00",
            temp_c: 38,
            temp_f: 100.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 329,
            wind_dir: "NNW",
            pressure_mb: 994,
            pressure_in: 29.37,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 0,
            feelslike_c: 37.1,
            feelslike_f: 98.8,
            windchill_c: 38,
            windchill_f: 100.5,
            heatindex_c: 37.1,
            heatindex_f: 98.8,
            dewpoint_c: -7.5,
            dewpoint_f: 18.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15,
            gust_kph: 24.2,
            uv: 1,
          },
          {
            time_epoch: 1717092000,
            time: "2024-05-30 23:00",
            temp_c: 36.6,
            temp_f: 98,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 1,
            wind_dir: "N",
            pressure_mb: 995,
            pressure_in: 29.37,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 6,
            cloud: 0,
            feelslike_c: 35.2,
            feelslike_f: 95.4,
            windchill_c: 36.6,
            windchill_f: 98,
            heatindex_c: 35.2,
            heatindex_f: 95.4,
            dewpoint_c: -6,
            dewpoint_f: 21.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.5,
            gust_kph: 24.9,
            uv: 1,
          },
        ],
      },
      {
        date: "2024-05-31",
        date_epoch: 1717113600,
        day: {
          maxtemp_c: 47.9,
          maxtemp_f: 118.2,
          mintemp_c: 32.2,
          mintemp_f: 89.9,
          avgtemp_c: 40.7,
          avgtemp_f: 105.3,
          maxwind_mph: 15.9,
          maxwind_kph: 25.6,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 7,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 11,
        },
        astro: {
          sunrise: "04:58 AM",
          sunset: "07:02 PM",
          moonrise: "12:47 AM",
          moonset: "12:27 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: 47,
          is_moon_up: 1,
          is_sun_up: 1,
        },
        hour: [
          {
            time_epoch: 1717095600,
            time: "2024-05-31 00:00",
            temp_c: 35.6,
            temp_f: 96,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 25,
            wind_dir: "NNE",
            pressure_mb: 995,
            pressure_in: 29.37,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 7,
            cloud: 0,
            feelslike_c: 33.9,
            feelslike_f: 92.9,
            windchill_c: 35.6,
            windchill_f: 96,
            heatindex_c: 33.9,
            heatindex_f: 92.9,
            dewpoint_c: -4.9,
            dewpoint_f: 23.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.6,
            gust_kph: 21.9,
            uv: 1,
          },
          {
            time_epoch: 1717099200,
            time: "2024-05-31 01:00",
            temp_c: 34.6,
            temp_f: 94.2,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 56,
            wind_dir: "ENE",
            pressure_mb: 994,
            pressure_in: 29.36,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 8,
            cloud: 0,
            feelslike_c: 32.7,
            feelslike_f: 90.8,
            windchill_c: 34.6,
            windchill_f: 94.2,
            heatindex_c: 32.7,
            heatindex_f: 90.8,
            dewpoint_c: -4.3,
            dewpoint_f: 24.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12.1,
            uv: 1,
          },
          {
            time_epoch: 1717102800,
            time: "2024-05-31 02:00",
            temp_c: 33.8,
            temp_f: 92.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 102,
            wind_dir: "ESE",
            pressure_mb: 994,
            pressure_in: 29.36,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 8,
            cloud: 0,
            feelslike_c: 31.7,
            feelslike_f: 89.1,
            windchill_c: 33.8,
            windchill_f: 92.8,
            heatindex_c: 31.7,
            heatindex_f: 89.1,
            dewpoint_c: -4.4,
            dewpoint_f: 24,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.6,
            uv: 1,
          },
          {
            time_epoch: 1717106400,
            time: "2024-05-31 03:00",
            temp_c: 33,
            temp_f: 91.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 97,
            wind_dir: "E",
            pressure_mb: 994,
            pressure_in: 29.37,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 9,
            cloud: 0,
            feelslike_c: 30.9,
            feelslike_f: 87.6,
            windchill_c: 33,
            windchill_f: 91.4,
            heatindex_c: 30.9,
            heatindex_f: 87.6,
            dewpoint_c: -4.3,
            dewpoint_f: 24.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.2,
            gust_kph: 19.7,
            uv: 1,
          },
          {
            time_epoch: 1717110000,
            time: "2024-05-31 04:00",
            temp_c: 32.5,
            temp_f: 90.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 111,
            wind_dir: "ESE",
            pressure_mb: 995,
            pressure_in: 29.37,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 9,
            cloud: 0,
            feelslike_c: 30.3,
            feelslike_f: 86.5,
            windchill_c: 32.5,
            windchill_f: 90.4,
            heatindex_c: 30.3,
            heatindex_f: 86.5,
            dewpoint_c: -5,
            dewpoint_f: 23.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.9,
            gust_kph: 15.9,
            uv: 1,
          },
          {
            time_epoch: 1717113600,
            time: "2024-05-31 05:00",
            temp_c: 32.2,
            temp_f: 89.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 106,
            wind_dir: "ESE",
            pressure_mb: 995,
            pressure_in: 29.39,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 8,
            cloud: 0,
            feelslike_c: 30,
            feelslike_f: 85.9,
            windchill_c: 32.2,
            windchill_f: 89.9,
            heatindex_c: 30,
            heatindex_f: 85.9,
            dewpoint_c: -5.5,
            dewpoint_f: 22,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8,
            gust_kph: 12.9,
            uv: 8,
          },
          {
            time_epoch: 1717117200,
            time: "2024-05-31 06:00",
            temp_c: 33.6,
            temp_f: 92.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 133,
            wind_dir: "SE",
            pressure_mb: 996,
            pressure_in: 29.41,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 7,
            cloud: 0,
            feelslike_c: 31.5,
            feelslike_f: 88.8,
            windchill_c: 33.6,
            windchill_f: 92.5,
            heatindex_c: 31.5,
            heatindex_f: 88.8,
            dewpoint_c: -6,
            dewpoint_f: 21.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.3,
            gust_kph: 18.1,
            uv: 8,
          },
          {
            time_epoch: 1717120800,
            time: "2024-05-31 07:00",
            temp_c: 36.7,
            temp_f: 98.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 170,
            wind_dir: "S",
            pressure_mb: 997,
            pressure_in: 29.43,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 6,
            cloud: 0,
            feelslike_c: 35.4,
            feelslike_f: 95.6,
            windchill_c: 36.7,
            windchill_f: 98.1,
            heatindex_c: 35.4,
            heatindex_f: 95.6,
            dewpoint_c: -6.7,
            dewpoint_f: 19.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.3,
            uv: 9,
          },
          {
            time_epoch: 1717124400,
            time: "2024-05-31 08:00",
            temp_c: 40,
            temp_f: 104.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 197,
            wind_dir: "SSW",
            pressure_mb: 997,
            pressure_in: 29.44,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 0,
            feelslike_c: 40,
            feelslike_f: 104,
            windchill_c: 40,
            windchill_f: 104.1,
            heatindex_c: 40,
            heatindex_f: 104,
            dewpoint_c: -5.9,
            dewpoint_f: 21.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.7,
            gust_kph: 12.4,
            uv: 10,
          },
          {
            time_epoch: 1717128000,
            time: "2024-05-31 09:00",
            temp_c: 42.7,
            temp_f: 108.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 997,
            pressure_in: 29.44,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 2,
            feelslike_c: 44.1,
            feelslike_f: 111.5,
            windchill_c: 42.7,
            windchill_f: 108.9,
            heatindex_c: 44.1,
            heatindex_f: 111.5,
            dewpoint_c: -4.2,
            dewpoint_f: 24.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.7,
            gust_kph: 12.4,
            uv: 10,
          },
          {
            time_epoch: 1717131600,
            time: "2024-05-31 10:00",
            temp_c: 44.9,
            temp_f: 112.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 239,
            wind_dir: "WSW",
            pressure_mb: 997,
            pressure_in: 29.44,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 2,
            feelslike_c: 47.8,
            feelslike_f: 118,
            windchill_c: 44.9,
            windchill_f: 112.9,
            heatindex_c: 47.8,
            heatindex_f: 118,
            dewpoint_c: -2.3,
            dewpoint_f: 28,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 10,
          },
          {
            time_epoch: 1717135200,
            time: "2024-05-31 11:00",
            temp_c: 46.3,
            temp_f: 115.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 242,
            wind_dir: "WSW",
            pressure_mb: 996,
            pressure_in: 29.42,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 2,
            feelslike_c: 50.3,
            feelslike_f: 122.5,
            windchill_c: 46.3,
            windchill_f: 115.4,
            heatindex_c: 50.3,
            heatindex_f: 122.5,
            dewpoint_c: -1.3,
            dewpoint_f: 29.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9,
            gust_kph: 14.5,
            uv: 11,
          },
          {
            time_epoch: 1717138800,
            time: "2024-05-31 12:00",
            temp_c: 47.4,
            temp_f: 117.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 240,
            wind_dir: "WSW",
            pressure_mb: 996,
            pressure_in: 29.4,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 8,
            feelslike_c: 52.2,
            feelslike_f: 126,
            windchill_c: 47.4,
            windchill_f: 117.3,
            heatindex_c: 52.2,
            heatindex_f: 126,
            dewpoint_c: -1.4,
            dewpoint_f: 29.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.6,
            gust_kph: 17,
            uv: 11,
          },
          {
            time_epoch: 1717142400,
            time: "2024-05-31 13:00",
            temp_c: 47.8,
            temp_f: 118,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 234,
            wind_dir: "SW",
            pressure_mb: 995,
            pressure_in: 29.38,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 14,
            feelslike_c: 52.9,
            feelslike_f: 127.3,
            windchill_c: 47.8,
            windchill_f: 118,
            heatindex_c: 52.9,
            heatindex_f: 127.3,
            dewpoint_c: -1.6,
            dewpoint_f: 29.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.1,
            gust_kph: 21.1,
            uv: 11,
          },
          {
            time_epoch: 1717146000,
            time: "2024-05-31 14:00",
            temp_c: 47.9,
            temp_f: 118.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 226,
            wind_dir: "SW",
            pressure_mb: 994,
            pressure_in: 29.35,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 11,
            feelslike_c: 53.2,
            feelslike_f: 127.7,
            windchill_c: 47.9,
            windchill_f: 118.2,
            heatindex_c: 53.2,
            heatindex_f: 127.7,
            dewpoint_c: -1.3,
            dewpoint_f: 29.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.4,
            gust_kph: 21.5,
            uv: 11,
          },
          {
            time_epoch: 1717149600,
            time: "2024-05-31 15:00",
            temp_c: 47.8,
            temp_f: 118.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.2,
            wind_kph: 18,
            wind_degree: 220,
            wind_dir: "SW",
            pressure_mb: 993,
            pressure_in: 29.33,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 11,
            feelslike_c: 53,
            feelslike_f: 127.4,
            windchill_c: 47.8,
            windchill_f: 118.1,
            heatindex_c: 53,
            heatindex_f: 127.4,
            dewpoint_c: -0.8,
            dewpoint_f: 30.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.9,
            gust_kph: 20.7,
            uv: 11,
          },
          {
            time_epoch: 1717153200,
            time: "2024-05-31 16:00",
            temp_c: 47.5,
            temp_f: 117.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 211,
            wind_dir: "SSW",
            pressure_mb: 993,
            pressure_in: 29.31,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 5,
            cloud: 16,
            feelslike_c: 52.4,
            feelslike_f: 126.2,
            windchill_c: 47.5,
            windchill_f: 117.4,
            heatindex_c: 52.4,
            heatindex_f: 126.2,
            dewpoint_c: -0.4,
            dewpoint_f: 31.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.2,
            gust_kph: 22.8,
            uv: 11,
          },
          {
            time_epoch: 1717156800,
            time: "2024-05-31 17:00",
            temp_c: 46.6,
            temp_f: 115.9,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 993,
            pressure_in: 29.31,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 6,
            cloud: 29,
            feelslike_c: 50.8,
            feelslike_f: 123.4,
            windchill_c: 46.6,
            windchill_f: 115.9,
            heatindex_c: 50.8,
            heatindex_f: 123.4,
            dewpoint_c: 0.3,
            dewpoint_f: 32.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17,
            gust_kph: 27.3,
            uv: 11,
          },
          {
            time_epoch: 1717160400,
            time: "2024-05-31 18:00",
            temp_c: 44.6,
            temp_f: 112.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 267,
            wind_dir: "W",
            pressure_mb: 993,
            pressure_in: 29.32,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 7,
            cloud: 16,
            feelslike_c: 47.2,
            feelslike_f: 116.9,
            windchill_c: 44.6,
            windchill_f: 112.2,
            heatindex_c: 47.2,
            heatindex_f: 116.9,
            dewpoint_c: 1.9,
            dewpoint_f: 35.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.8,
            gust_kph: 31.8,
            uv: 10,
          },
          {
            time_epoch: 1717164000,
            time: "2024-05-31 19:00",
            temp_c: 42,
            temp_f: 107.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 295,
            wind_dir: "WNW",
            pressure_mb: 993,
            pressure_in: 29.34,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 9,
            cloud: 13,
            feelslike_c: 43,
            feelslike_f: 109.4,
            windchill_c: 42,
            windchill_f: 107.6,
            heatindex_c: 43,
            heatindex_f: 109.4,
            dewpoint_c: 2.1,
            dewpoint_f: 35.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.2,
            gust_kph: 26.1,
            uv: 10,
          },
          {
            time_epoch: 1717167600,
            time: "2024-05-31 20:00",
            temp_c: 40.6,
            temp_f: 105,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 42,
            wind_dir: "NE",
            pressure_mb: 994,
            pressure_in: 29.36,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 9,
            cloud: 25,
            feelslike_c: 40.8,
            feelslike_f: 105.4,
            windchill_c: 40.6,
            windchill_f: 105,
            heatindex_c: 40.8,
            heatindex_f: 105.4,
            dewpoint_c: 1.7,
            dewpoint_f: 35.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1,
          },
          {
            time_epoch: 1717171200,
            time: "2024-05-31 21:00",
            temp_c: 40,
            temp_f: 104.1,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 15.9,
            wind_kph: 25.6,
            wind_degree: 84,
            wind_dir: "E",
            pressure_mb: 995,
            pressure_in: 29.4,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 10,
            cloud: 29,
            feelslike_c: 40,
            feelslike_f: 103.9,
            windchill_c: 40,
            windchill_f: 104.1,
            heatindex_c: 40,
            heatindex_f: 103.9,
            dewpoint_c: 2.7,
            dewpoint_f: 36.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 26.5,
            gust_kph: 42.7,
            uv: 1,
          },
          {
            time_epoch: 1717174800,
            time: "2024-05-31 22:00",
            temp_c: 39.8,
            temp_f: 103.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 11,
            wind_kph: 17.6,
            wind_degree: 97,
            wind_dir: "E",
            pressure_mb: 995,
            pressure_in: 29.4,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 11,
            cloud: 7,
            feelslike_c: 39.6,
            feelslike_f: 103.3,
            windchill_c: 39.8,
            windchill_f: 103.7,
            heatindex_c: 39.6,
            heatindex_f: 103.3,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.8,
            gust_kph: 31.8,
            uv: 1,
          },
          {
            time_epoch: 1717178400,
            time: "2024-05-31 23:00",
            temp_c: 39.1,
            temp_f: 102.4,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 92,
            wind_dir: "E",
            pressure_mb: 995,
            pressure_in: 29.39,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 11,
            cloud: 48,
            feelslike_c: 38.7,
            feelslike_f: 101.6,
            windchill_c: 39.1,
            windchill_f: 102.5,
            heatindex_c: 38.7,
            heatindex_f: 101.6,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 20,
            gust_kph: 32.2,
            uv: 1,
          },
        ],
      },
    ],
  },
};
